# Python - A brief introduction with regard to using Pyomo

#### Content:
1. [How to use this notebook](#1.-How-to-use-this-notebook)
2. [Variables and syntax](#2.-Variables-and-syntax)
3. [Operators](#3.-Operators)
4. [Data structures](#4.-Data-structures)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[List](#4.1-List)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Tuple](#4.2-Tuple)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Dictionary](#4.3-Dictionary)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Set](#4.4-Set)
5. [Importing](#5.-Importing)
6. [The search for truth and branching (if-else)](#6.-The-search-for-truth-and-branching)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Exkurs: A word about indentation](#Exkurs:-A-word-about-indentation)
7. [Looping](#7.-Looping)
8. [Comprehensions](#8.-Comprehensions)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[List comprehension](#8.1-List-comprehension)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Dictionary comprehension](#8.2-Dictionary-comprehension)
<br> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[Using comprehensions to calculate the sum product](#8.3-Using-comprehensions-to-calculate-the-sum-product)
9. [Numpy](#9.-Numpy)

## 1. How to use this notebook

#### How to run code interactively
1. Click into the grey area with the code. A border around the cell appears with a __green__ left side. <br/>If the color is blue instead of green, make sure you click into the grey shaded area.
2. Press __Ctrl + Enter__ to run the code in the cell or __Shift + Enter__ to run the code and subsequetly select the next cell.
3. Note how the number in the brackets of __In[ ]__ changes in the top left of the cell. The number increases with each executed cell and allows you to easily track in which order the cells were executed.

In [ ]:
print("Click in this gray area and press CTRL + ENTER to run me interactively!")
print(2 + 2)

#### Some useful commands
- To reset all cell outputs, click "Cell" -> "All Output" -> "Clear"
- To reset the kernel (the python interpreter), click "Kernel" -> "Restart & Clear Output"
- To rename your notebook, click "File" -> "Rename"
- To export your notebook to different file formats, click "File" -> "Download as"
- To move a selected cell up or down, click the up or down button in the taskbar above.

#### How to insert a new cell
Maybe you want to experiment further or take some notes. In that case you can easily extend the notebook with new cells.
1. Click on an existing cell. If that cell contains grey shaded code area, do to __not__ click into this area. A border around the cell appears with a __blue__ left side.
2. You can now press the __a or b__ keys to insert a new cell above or below respectively. If you want to remove the current cell, press the __d__ key twice.

#### How to toggle between a markdown and a code cell
Markdown cells hold text for explanation. Code cells hold code that can be interactively executed. You recognize code cells easily by the grey shaded area and the __In[ ]:__ to their left.
1. Click on an existing cell. If that cell contains grey shaded code area, be sure to __not__ click into this area. A border around the cell appears with a __blue__ left side.
2. Press the __m or y__ key to change the cell to a markdown or code cell respectively.

#### How to style markdown cells
Double-click a markdown cell to go into edit mode. You will see the font changing and some extra symbols will appear. These extra symbols (e.g. ###) are used for styling purposes. Check the existing markdown cells or check this <a href="https://medium.com/ibm-data-science-experience/markdown-for-jupyter-notebooks-cheatsheet-386c05aeebed" target="_blank">awesome cheatsheet</a>. In addition you can use common HTML markup, like the &lt;a&gt; tag used for the link above! When you finish editing, don't forget to press __Ctrl + Enter__ to apply the styling and close edit mode.

## 2. Variables and syntax

Similar to Matlab and R, Python is a dynamically typed language. That means, variables do not need to be declared with a specified datatype (integer, string, float) before being used. Also the datatypes held by a variable can change on the fly. A variable previously assigned to a number can subsequently be assigned to a string without any problems.

In [ ]:
a = 5
b = 7
c = a + b
print(c)

In [ ]:
a = 5
print(a)
a = "John"
print(a)

#### Note:
- Compared to Matlab, there are no semicolons (;) at the end of a line.
- For strings, both single (') or double (") quotation marks are fine.
- A hashtag (#) indicates a line of comments.
- The function print() is used to show the value of a variable or expression. In the jupyter notebook, the value of the last line will be printed by default if not assigned to a variable.

## 3. Operators

Python supports all common operators one may expect. The only syntactic speciality is the power operator, which is a double star (**) instead of the more commonly used caret (^).

In [ ]:
print(1 + 4) # Addition
print(6 - 2) # Subtraction
print(4 * 3) # Multiplication
print(8 / 3) # Division
print(8 // 3) # Floor division
print(2 ** 3) # Exponentiation
print(10 % 3) # Modulus

All of these operators have also an assignment operator equivalent, which performs the operation and assigns the result back to the variable in one step. They consist of the operator followed by the equal sign, e.g. +=, -=, *=, etc.

In [ ]:
# Normal operator +
a = 3
a = a + 2
print(a)

# Assignment operator +=
a = 3
a += 2
print(a)

Some operators work differently on numbers and strings. Most notably, the + operator is used for concatenation and the * operator is used for repetition when used with strings.

In [ ]:
a = "Hello"
b = "World"
print(a + b)
print(3 * a)

Python will __not__ let you concatenate numbers and strings together! Use the str() function to convert a number to a string prior to concatenation.

In [ ]:
a = "My age is "
b = 54
print(a + b) # Error!

In [ ]:
print(a + str(b)) # Works!

### A note on error messages:
When an error occurs, Python usually provides you with a detailed description of where something went wrong. __Error messages are your friend!__ Take some time to study the report and try to figure out in what line the error occured and what kind of error it is. Learning to efficiently deal with error reports will save you a lot of frustration when writing your own programs.

## 4. Data structures

Data structures are used to store data. Depending on the type of data, one data structure might be more suited than another. In the following, we will have a brief look at four different commonly used native python data structures:
- [List](#4.1-List)
- [Tuple](#4.2-Tuple)
- [Dictionary](#4.3-Dictionary)
- [Set](#4.4-Set)

### 4.1 List

A list is a collection of items, that is __ordered__ and __mutable__. Lists are useful if your data is somehow ordered (e.g. a timeseries), because it makes selecting items in relation to each other very efficient via indexing.

Square brackets [ ] are used for list creation as well as indexing, i.e. accessing elements in the list.

In [ ]:
my_list = [1, 2, 3, 9, 12]
print(my_list)

List items can be of different types. It is even possible to "nest" one list in another one.

In [ ]:
my_list = [2, 'hello', [5,4,3], 5, 77, 3, 12, 13]
print(my_list)

As __python is 0-based__, the first element in a list is at position list[0]. Access the first element of the inner list by using a second square bracket. The more to the right a square bracket, the deeper nested the accessed element is.

In [ ]:
print(my_list[0])
print(my_list[2])
print(my_list[2][0])
print(my_list[2][1])

Python supports also negative indexing. The index -1 always returns the last element.

In [ ]:
my_list[-1]

Because lists are ordered, it is also possible to extract multiple adjacent items at once by using a colon (:). This is called slicing. 
- The start index is inclusive (included in the slice).
- The end index is exclusive (not included in the slice).
- Omitting the end index slices until the end of the list. 
- Omitting the start index slices from the start of the list.
- Don't forget  that python is 0-based.

In [ ]:
print(my_list)
print('-'*20)
print(my_list[4:6])
print(my_list[4:])
print(my_list[:6])

Items can be easily replaced by assigning a new item to the desired position.

In [ ]:
print(my_list)
my_list[0] = 'New York'
print(my_list)

Test if a list contains an element by using the __in__ keyword.

In [ ]:
print("hello" in my_list)
print(-999 in my_list)

#### Useful list operations
- Lists can dynamically grow and shrink using append() and pop().
- Lists can be easily reversed and sorted using reverse() and sort().
- The number of elements can be found with the len() function.
- Lists support the + and * operators for concatenation and repetition.

Note below how append(), pop(), reverse() and sort() change the list __in-place__. That means the list itself is changed and these functions do not return a modified result list. Because such in-place operations are possible, lists are called mutable.

A summary of all list operations can be found <a href="https://www.programiz.com/python-programming/methods/list" target="_blank">here</a>.

In [ ]:
my_list = [4, 2, 1, 5]
print(my_list)
my_list.append(7) # append(x) appends x at the end of the list. 
print(my_list)
popped_element = my_list.pop() # pop() returns the last element and removes it from the list.
print(my_list)
print(popped_element)

In [ ]:
print(my_list)
my_list.reverse() # reverse(x) reverses the elements in x.
print(my_list)
my_list.sort() # sort(x) sorts the elements in x.
print(my_list)

In [ ]:
nr_items = len(my_list) # len(x) returns the number of elements in x.
print(nr_items)

In [ ]:
# The + operator allows to concatenate lists.
a = [2, 3, 4]
b = [5, 6, 7]
c = a + b
print(c)

In [ ]:
# The * operator allows to repeate lists.
a * 3

### Mutability caveats
The mutable nature of lists can lead to some confusing behaviour for beginners. For example consider the following example that assigns a number to a, then assigns a to b and finally changes the value associated with b. In the end, a and b are different, which is intuitive:

In [ ]:
a = 7
b = a
print(b)
b = 4
print(a)
print(b)

However, watch what happens when doing the same to lists:

In [ ]:
a = [1,2,3]
b = a
print(b)
b[1] = 7
print(a)
print(b)

By just changing b we also modified a! How is this possible? With a small modification (note the a.copy()) it works as expected:

In [ ]:
a = [1,2,3]
b = a.copy()
print(b)
b[1] = 7
print(a)
print(b)

The explanation is rooted in the very fundamental way of what variables in python really are and is out of scope for this tutorial. __Just remember that with mutable datatypes an assignment (=) is not equivalent with creating a independent copy. To achieve this use .copy()!__ In case of nested structures you might want to have a look at the deepcopy module.

If you would like to dig deeper, I'd recommend this <a href="https://standupdev.com/wiki/doku.php?id=python_tuples_are_immutable_but_may_change" target="_blank">fantastic article</a>.

### 4.2 Tuple

A tuple is a collection of items, that is __ordered__ and __immutable__. Compared to lists, they cannot be changed once they have been created. Although tuples have many uses, we will only use them as multi-dimensional keys for dictionaries (next section), because dictionary keys must be immutable.

- Round brackets ( ) are used to create a tuple. 
- Square brackets [ ] are used to access elements.
- Indexing and slicing is the same as with lists.
- Just like lists, tuples can hold all kinds of different data.

A summary of all tuple operations can be found <a href="https://www.programiz.com/python-programming/methods/tuple" target="_blank">here</a>.

In [ ]:
my_tuple = (1, 3, 5, 'hello')
print(my_tuple[1])

Compared to lists, it is not possible to change an element of a tuple.

In [ ]:
my_tuple[1] = 9 # Error!

### 4.3 Dictionary

A dictionary is a collection of items, that is __unordered__ and __mutable__. Each item consists of a __key:value__ pair, whereby the key is used to look up the associated value. Dictionaries are useful if your data is unordered and has some meaningful labels that can act as keys. An example would be customer data (value) with an associated unique ID (key). 

One advantage of dictionaries over lists is their lookup speed. Even with millions of items, searching for the value associated with a specific key is blazingly fast. The same operation would take a lot longer on a list of similar size. A second advantage is the nature of the key:value pair, which would be very cumbersome to implement using only lists.

- Curly brackets { } are used for dictionary creation. 
- The key is separated from the value by a colon (:). 
- Key:value pairs are separated by commas (,). 
- A key can be numeric or a string. 
- The value can be of any type, e.g. list, another dictionary, numeric or string.

In [ ]:
my_dict = {"key1":"value1", "key2":234, 99:[1,2,3]}
print(my_dict)

Test if a key exists with the __in__ keyword.

In [ ]:
print("key1" in my_dict)
print("key4" in my_dict)

Values can be accessed via the corresponding key either using square brackets [] or the get() function.

In [ ]:
print(my_dict["key1"])
print(my_dict[99])
print(my_dict["key2"])

If the key does not exists, a "KeyError" error is raised when using the square brackets.

In [ ]:
my_dict["key4"]

Alternatively, get("key", "default") can be used to get the value associated with "key". __Compared to the [ ] notation, a missing key does not raise an error, but returns the value specied as "default".__

In [ ]:
value = my_dict.get("key1", None) # key1 exists -> associated value ("value1") is returned
print(value)
value = my_dict.get("key4", None) # key4 does not exist -> None is returned
print(value)

#### Note: 
The keyword __None__ in python is a valid constant, however it has no value and will always evaluate to False (see later). It basically means "Nothing" and is roughly comparable to R's NULL.

A new key:value pair is added by assigning the value to a key that does not exist yet. __If a key already exists, the existing associated value is overwritten.__

In [ ]:
print(my_dict)
my_dict["new_key"] = 66
print(my_dict)
my_dict["key1"] = -763
print(my_dict)

Tuples are valid dictionary keys. They can be used as __multidimensional keys__. Note how the round brackets of tuples can be omitted when retrieving the values.

In [ ]:
my_dict = {('Marc', 1): 44, ('Marc', 2): 21, (5,4): -7}
print(my_dict)

In [ ]:
my_dict['Marc', 2]

#### Useful dictionary operations

- The number of key:value pairs can be found with the len() function.
- Keys and values can easily be extracted using the keys() and values() function respectively. Key:value pairs are extracted using the items() function.
- Merge two dictionaries using the update() function.
- Easily return and remove the value associated with a key using the pop() function.

Just like with lists, note below how update() and pop() change the dictionary __in-place__. That means the dictionary itself is changed and these functions do not return a result that needs to be assigned to a variable again.

A summary of all dictionary operations can be found <a href="https://www.programiz.com/python-programming/methods/dictionary" target="_blank">here</a>.

In [ ]:
my_dict = {'Marc': 34, 'Anna': 66, 'Pete': 98, 'Elena':32}
print(my_dict)
nr_items = len(my_dict)
print(nr_items)

In [ ]:
all_keys = my_dict.keys() # Return all keys from my_dict. Using values() would do the same for the values.
list(all_keys) # Convert them to a list.

In [ ]:
# Update dict_1 with the key:values of dict_2. For identical keys, the value of dict_1 is overwritten.
dict_1 = {'a':4, 'b':5}
dict_2 = {'c':6, 'b':9}
dict_1.update(dict_2)
print(dict_1)

In [ ]:
# pop(key, default) removes the value of the corresponding key from the dictionary and returns it.
# If the key does not exist, the default value is returned instead. Note the similarity to get(key, default).
print(dict_1)
popped_element_1 = dict_1.pop('b', None) # key exists
print(dict_1)
print(popped_element_1)
popped_element_2 = dict_1.pop('z', None) # key does not exist
print(popped_element_2)

### 4.4 Set

Sets are __unordered__, __mutable__ collections of __unique__ items.

#### Creation and indexing
- Curly brackets { } or the set() function are used for set creation.
- As they are unordered, sets do not support indexing.
- Lists can easily be converted to sets and vice versa.

Sets have a lot of interesting use cases, but we will only demonstrate the common case of extracting the unique elements from a list using a set:

In [ ]:
# List with duplicates
list_with_duplicates = [1, 2, 3, 1, 2, 1, 4]
print(list_with_duplicates)
# Convert to a set, thus removing duplicates
my_set = set(list_with_duplicates)
print(my_set)
# Convert set back to a list (note in the output how the curly brackets { } change to square brackets [ ])
list_without_duplicates = list(my_set)
print(list_without_duplicates)

A summary of all set operations can be found <a href="https://www.programiz.com/python-programming/methods/set" target="_blank">here</a>.

## 5. Importing

After downloading and installing a package via a package manager (pip or conda), we __import__ that code to make use of it in our own application. There are several ways how we can do this, but the common denominator to all is the use of the keyword __import__. Importing all needed modules at the very top of your own module is considered good practise.

We will use the "random" module of the standard library, which contains a bunch of functions allowing us to do literally random stuff. The __shuffle()__ function takes an array and randomly changes its items in-place. As this module is in the standard library, we do not need to first install it as it comes bundled with standard python installation.

#### Module or package?
Every file with python code is a module with the same name as the file (without the \*.py extension) and can be easily imported into other modules. A collection of modules grouped in a directory with a special \_\_init\_\_.py file is called a package. However, a lot of people use these names interchangeably. There is much more to that topic <a href="https://realpython.com/python-modules-packages/" target="_blank">here</a>.

### 5.1 import random
This is a very common way to import a module. Note that we use the name of the module as prefix to call functions (in that case shuffle). So each function x from random we can call as random.x().

In [ ]:
import random

my_list = [1, 2, 3, 4]
print(my_list)
random.shuffle(my_list)
print(my_list)

### 5.2 import random as rnd
This is basically the same as "import random", but we assign a custom name to the imported module. We then use this (often shorter) name as prefix when using a module function. This is often used when we make extensive use of many functions of a package, e.g. when working with numpy (import numpy as np), pandas (import pandas as pd) or pyplot (import matplotlib.pyplot as plt).

In [ ]:
import random as rnd

my_list = [1, 2, 3, 4]
print(my_list)
rnd.shuffle(my_list)
print(my_list)

In [ ]:
import random as rnd
import matplotlib.pyplot as plt

x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [1, 1, 2, 3, 5, 8, 13, 21, 34]
rnd.shuffle(y)
plt.plot(x, y)
plt.show()

### 5.3 from random import shuffle
It is possible to import a specific function from a module. That way no prefix is needed, as the function is completely copied to our module. We can then use the function as if it was defined in our module.

In [ ]:
from random import shuffle

my_list = [1, 2, 3, 4]
print(my_list)
shuffle(my_list)
print(my_list)

### 5.4 from random import *
This is similar to "from random import shuffle", but the star (\*) means that we not only import the function shuffle, but __every__ function of that module into our module. We can then use every function of this module without prefix, as if we defined them in our modules. This import statement is generally considered bad practise, because it pollutes the namespace of our module with a potentially huge amount of functions and variables which can lead to a lot of confusion.

However, for very specialized use cases that make heavy use of a single module, this import statement might be suitable. We use it in the case of the pyomo optimization package.

In [ ]:
from random import *

my_list = [1, 2, 3, 4]
print(my_list)
shuffle(my_list)
print(my_list)

## 6. The search for truth and branching

Branching is the process of making decisions in a program using if-else statements. To that end, an expression must evaluate to either __True__ or __False__.

### 6.1 Is it True or False...?
Comparisons luckily work as in any other language:

In [ ]:
print(3 > 3)
print(3 >= 3)
print(4 == 5)
print(4 != 5)

In Python, __everything__ can be evaluated as either True or False. This has some interesting implications, as it allows us to test for empty strings, empty lists, empty dictionaries, empty objects or the constant None, which all evaluate to false when put to a boolean test. The function __bool()__ can be used to force evaluation of an expression:

In [ ]:
# List
print(bool([]))
print(bool([2, "hello"]))

In [ ]:
# Dictionary
print(bool({}))
print(bool({'key1':"hello"}))

In [ ]:
# String
print(bool(""))
print(bool("hello"))

In [ ]:
# Numeric
print(bool(0))
print(bool(0.0))
print(bool(1.3))

In [ ]:
# None
print(bool(None))

__Boolean logic__ uses the keywords __and__, __or__ and __not__ to evaluate multiple comparisons:

In [ ]:
# AND evaluates to True only if both operands are True
print(True and True)
print(False and True)
print(False and False)
print(5 > 3 and 7 < 12)

In [ ]:
# OR evaluates to True if one or both operands are True
print(True or True)
print(False or True)
print(False or False)
print(5 > 3 or 7 < 12)

In [ ]:
# NOT negates the evaluation
print(not True)
print(not(True and False))
print(not None)

### 6.2 If - elif - else
The __if__ statement is followed by a boolean expression that will eventually evaluate to True or False and is terminated by a colon (:). Accidentally omitting the colon is one of the most common errors for beginners.

In [ ]:
# If the condition is True, the if block gets executed.
# If the condition is False, the if block is skipped.
x = 6
if x < 9:
    print("x is smaller than 9")
if x < 5:
    print("x is smaller than 5")

<hr>

## Exkurs: A word about indentation

In the cell above you might have asked yourself how python knows what lines should only be executed if the if statement is true and what lines should be executed everytime as part of the main script. There are no curly brackets (hello java, R and the C family) and no keywords like "end" (hello Matlab and Julia).

The answer: __indentation__

Python programs are structured by their indentation, meaning how many whitespaces there are before the line starts. All consecutive lines with same indentations are called a suite (or block) and belong together. This design decision forces the programmer to have a consisten structure and is responsible for the clean and easy-to-read look of the language. 

__By the way:__ In this notebook you may also use tabs to indent your code. Jupyter will automatically convert each tab to 4 whitespaces.

<hr>

In [ ]:
x = 4
if x < 9:
    print("x is smaller than 9")
    print("I am indented and therefore part of the if block!")
print("I am not indented and therefore I get executed every time!")

In [ ]:
x = 10
if x < 9:
    print("x is smaller than 9")
    print("I am indented and therefore part of the if block!")
print("I am not indented and therefore I get executed every time!")

An if block can be followed by an __else__ block, which is executed whenever the statement evaluates to False:

In [ ]:
x = 10
if x < 9:
    print("x is smaller than 9")
else:
    print("x is larger or equal than 9")

Comparisons can also be chained. An if block can be followed by an __elif__ block (else if). The elif condition is only evaluated, if the __first if condition evaluates to False__. If the elif condition evaluates to True, the elif block is executed. If the elif condition evaluates to False, the else block is excuted.

In [ ]:
x = 9
if x < 9:
    print("x is smaller than 9")
elif x == 9:
    print("x is exactly 9")
else:
    print("x is larger than 9")

## 7. Looping

We will only look at the __for-loop__, which is used to iterate (or traverse) over a sequence of values.

### 7.1 Looping over a list
__Version 1 - Direct assignment to loop variable:__ Each list element is assigned directly to the loop variable item in each iteration:

In [ ]:
my_list = [3, 2, 5, 4]
for item in my_list:
    print(item)

If the list to iterate over consists of __pairs of data__, python allows for simulaneous assignment via multiple loop variables:

In [ ]:
my_list = [[3,4], [7,8], [5,4]]
for first, second in my_list:
    print(str(first) + ' | ' + str(second))

The same of course works for tuples:

In [ ]:
my_list = [(3,4), (7,8), (5,4)]
for first, second in my_list:
    print(str(first) + ' | ' + str(second))

__Version 2 - Generation of consecutive integers to be used as list indices:__ The functions range() and len() are used to generate a list of consecutive integers in the form of (0, 1, 2 ..., len(list)-1) which are used as loop variable in each iteration to access the current element of the list:

In [ ]:
list(range(3,10))

If only one number is supported, the sequence will start from 0 up to that number (exclusive).

In [ ]:
list(range(10))

In [ ]:
my_list = [3, 2, 5, 4]
for k in range(len(my_list)):
    print(str(k) + ' can be used as index to access element ' + str(my_list[k]))

### 7.2 Looping over a dictionary
Iterating over a dictionary uses the function items() to produce a __sequence of key:value pairs__, which are assigned to the loop variables k and v respectively during each iteration in the example below:

In [ ]:
my_dict = {'Marc': 34, 'Anna': 66, 'Pete': 98, 'Elena':32}
for k, v in my_dict.items():
    print(str(k) + ' -> ' + str(v))

### 7.3 Break and continue statements
If a __break__ statement is executed in the body of a loop, the loop immediately terminates. The script will then continue after the loop body:

In [ ]:
# Iterate over my_list and check if each item evaluates to True.
# If item evaluates to False, exit loop and resume script after loop body.
my_list = [1, "samo", 5, None, 34, 64]
for item in my_list:
    if item:
        print("Item evaluated to True: " + str(item))
    else:
        print("Oh no! Item evaluated to False: " + str(item))
        print("Exit loop!")
        break
print("I am a statement after the loop body!")

If a __continue__ statement is executed in the body of a loop, the current iteration immediately terminates and the __next__ iteration starts:

In [ ]:
# Execute the loop 3 times (with k = 0, 1, 2) and print "ping" followed by "pong".
# If k == 1, print "SMASH" and execute continue, therefore skipping the "pong" in this iteration.
# Note how the third iteration is still executed normally.
for k in range(3):
    print("ping")
    if k == 1:
        print("SMASH")
        continue
    print("pong")

## 8. Comprehensions

### 8.1 List comprehension

Often we want to iterate over a sequence, process each item and then return a new list with the results. In that case python offers a special syntax construct called __list comprehension__, which is both more concise as well as more efficient for that special use case. A list comprehension consists of a somehow "flipped" for-loop enclosed by square brackets.

A list comprehension is nothing new, it really is just another way to write a for-loop. Hence, every list comprehension can be also written as a classic for-loop!

The following list comprehension squares all elements of a list:

In [ ]:
my_list = [1, 2, 3, 4, 5]

# List comprehension
squares = [i**2 for i in my_list]
print(squares)

# Classic way to write the list comprehension above:
squares = []
for i in my_list:
    squares.append(i**2)
print(squares)

It is also possible to __conditionally__ process elements using if-else statements. The example below only squares elements that are >= 3:

In [ ]:
my_list = [1, 2, 3, 4, 5]

# List comprehension
squares = [i**2 for i in my_list if i >= 3]
print(squares)

# Classic way to write the list comprehension above:
squares = []
for i in my_list:
    if i >= 3:
        squares.append(i**2)
print(squares)

It is also possible to use __nested for-loops__ in list comprehensions:

In [ ]:
card_values = ['2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A']
card_suits = ['hearts', 'spades', 'clubs', 'diamonds']

# List comprehension:
card_deck = [value + ' of ' + suit for value in card_values for suit in card_suits]
print(card_deck)
print('-' * 40)

# Classic way to write the list comprehension above:
card_deck = []
for suit in card_suits:
    for value in card_values:
        card_deck.append(value + ' of ' + suit)
print(card_deck)

### 8.2 Dictionary comprehension

Dictionary comprehensions are similar to list comprehensions. They are enclosed by curly brackets { } and they return a dictionary instead of a list. We will just scratch the surface with a simple example: Creating a new dictionary from a list of names - acting as keys - with associated values of 0.

In [ ]:
names = ['Peter', 'Sarah', 'Milow', 'Fred']
new_dict = {name:0 for name in names}
print(new_dict)

### 8.3 Using comprehensions to calculate the sum product

Pyomo makes heavy use of syntax that resembles list comprehensions in combination with the sum() function. This allows a concise calculation of the sum product, which is heavily used when formulating linear programming models.

You will notice the lack of square brackets [ ] around the list comprehension syntax when used within the sum() function. That is because technically speaking this construct is not a list comprehension but a generator comprehension. To elaborate on generators is out of scope here. Sufficient to say that they are very close to list comprehensions but more memory efficient when dealing with large datasets. If this does not satisfy you, go <a href="https://stackoverflow.com/questions/364802/how-exactly-does-a-generator-comprehension-work" target="_blank">here</a>.

In [ ]:
v1 = [2, 3, 4]
v2 = [5, 6, 7]
index_set = range(len(v1))

# Sum product calculated by comprehension
sum_product = sum(v1[m]*v2[m] for m in index_set)
print(sum_product)

# Classic way to write comprehension above:
sum_product = 0
for m in index_set:
    sum_product += v1[m] * v2[m]
print(sum_product)

As you can see, using the combination of sum() with list comprehension like syntax allows us to calculate the sum product in one line of code. As you will see, pyomo works with dictionary like data structures. Calculating the sum is straight forward:

In [ ]:
# Calculating sum over dictionary
my_dict = {'Peter':5, 'Sarah':4, 'Milow':2, 'Fred':7}
index_set = my_dict.keys()

summed = sum(my_dict[i] for i in index_set)
print(summed)

In the same way, also the sum product can be calculated from two dictionaries as long as they share the same keys:

In [ ]:
my_dict1 = {'Peter':5, 'Sarah':4, 'Milow':2, 'Fred':7}
my_dict2 = {'Peter':2, 'Sarah':1, 'Milow':4, 'Fred':2}
index_set = my_dict1.keys()

sum_product = sum(my_dict1[i] * my_dict2[i] for i in index_set)
print(sum_product)

It is also possible to calculate the sum product of a list and a dictionary, as long as the keys of the dictionary can be used as valid list indices. However, you should avoid this as it tends to get confusing really fast:

In [ ]:
my_dict = {3:2, 1:4, 0:2, 2:5}
my_list = [3, 2, 6, 4]
index_set = my_dict.keys()

sum_product = sum(my_dict[i] * my_list[i] for i in index_set)
print(sum_product)

#### Working with 2-dimensional dictionary keys
Working with tuples as multi-dimensional keys allows us to do rather complex calculations in a very concise and efficient way. In the following example, a dictionary with a 2-dimensional key consisting of a name and a choice is created. The corresponding values are all set to 1:

In [1]:
names = ['Peter', 'Sarah', 'Milow', 'Fred']
choices = [0, 1, 2]
name_choice_dict = { (name, choice):1 for name in names for choice in choices }
print(name_choice_dict)

{('Peter', 0): 1, ('Peter', 1): 1, ('Peter', 2): 1, ('Sarah', 0): 1, ('Sarah', 1): 1, ('Sarah', 2): 1, ('Milow', 0): 1, ('Milow', 1): 1, ('Milow', 2): 1, ('Fred', 0): 1, ('Fred', 1): 1, ('Fred', 2): 1}


Values of dictionaries with multi-dimensional keys can be accessed in the following way:

In [2]:
name_choice_dict['Sarah', 1]

1

Imagine we have a multiplier given for each name and we want to calculate the sum product over all names and choices, such that the multiplier is the same for all choices of a particular person. Such calculations are quite common when working with linear programming models, e.g. when specifying the objective function or the constraints in the face of hierarchically structured decision variables.

In [4]:
names = ['Peter', 'Sarah', 'Milow', 'Fred']
choices = [0, 1, 2]
multiplier = {'Peter':3, 'Sarah':7, 'Milow':1, 'Fred':2}

sum_product = sum(name_choice_dict[name, choice] * multiplier[name] for name in names for choice in choices)
print(sum_product)

39


## 9. Numpy

The creators are right when they state on their website that numpy is __the__ fundamental package for scientific computing with python that countless other packages depend upon. We will use numpy to prepare data for the optimization model and process the optimized results. Therefore we will only have a look at a very small portion of its functionality:
- Working with multidimensional arrays
- Boolean indexing
- Some useful functions

In [5]:
import numpy as np

### Numpy arrays
Numpy arrays are in many ways similar to Matlab's arrays. They offer less flexibility than lists, but working with them is much faster and ressource efficient. In addition they support some very neat features like multi-dimensional indexing or boolean masking.

#### Array creation routines
While lists can be extended or shrinked, arrays should be initialized to a fixed size. Numpy offers many possibilities to create an array with a specified initial value for subsequent processing. This process is called __preallocation__.

Some commonly used functions are zeros() and ones() to create an array of zeros and ones. The full() functions allows for a custom initial value. Passing an integer to these functions creates an 1-dimensional array (vector). To create multi-dimensional arrays, pass the functions a tuple containing the dimensions.

In [6]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [7]:
np.ones((5,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
np.full((2,3), -99)

array([[-99, -99, -99],
       [-99, -99, -99]])

It is possible to create an array directly from a nested list  using array():

In [9]:
np.array([[1,2,3], [9,8,7]])

array([[1, 2, 3],
       [9, 8, 7]])

#### Indexing and slicing
Indexing and slicing works the same as with lists. Similar to Matlab, multi-dimensional indexing and slicing is easy:

In [10]:
an_array = np.array([[1,2,3,4], [9,8,7,6]])
print(an_array)

[[1 2 3 4]
 [9 8 7 6]]


In [11]:
an_array[1,3]

6

In [12]:
an_array[0, 0:3]

array([1, 2, 3])

In [13]:
an_array[:, 3]

array([4, 6])

It is also possible to pass arbitrary indices to an array to extract the corresponding elements:

In [14]:
an_array[0, [3,1,2]]

array([4, 2, 3])

#### Boolean masking

Comparing an array to some value returns a new array containing boolean values (True/False) for each entry:

In [15]:
an_array > 3

array([[False, False, False,  True],
       [ True,  True,  True,  True]], dtype=bool)

The combination of the two numpy features above allows for __boolean masking__, which allows to extract a subset of an array based on one or several logical comparisons. As shown above, the comparison in the square brackets results in an array containing True/False. Subsequently, only the elements for which the comparison evaluated to True are extracted:

In [16]:
an_array[an_array > 3]

array([4, 9, 8, 7, 6])